# nixpacks.toml

[phases.setup]
# Устанавливаем Python и Poetry
nixPkgs = ["pkgs.python3", "pkgs.poetry"]

[phases.install]
# Даем четкие пошаговые инструкции для установки
cmds = [
  # 1. Создаем стандартное виртуальное окружение Python
  "python3 -m venv /opt/venv",
  # 2. Активируем его
  ". /opt/venv/bin/activate",
  # 3. Используем Poetry, чтобы сгенерировать requirements.txt из вашего pyproject.toml
  "poetry export -f requirements.txt --output requirements.txt --without-hashes",
  # 4. Устанавливаем все пакеты в наше активное окружение с помощью надежного pip
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
# Перед запуском скрипта мы снова активируем то же самое окружение
cmd = ". /opt/venv/bin/activate && python3 telegram_bot.py"
