# nixpacks.toml

[phases.setup]
# Указываем, что нам нужен Python и Poetry (менеджер пакетов)
nixPkgs = ["pkgs.python3", "pkgs.poetry"]

[phases.install]
# Указываем Railway, что для установки нужно использовать команду 'poetry install'
# Poetry очень хорошо кэширует зависимости, что ускоряет сборк
cmds = ["poetry install"]

[start]
# Указываем, как запускать бота через Poetry
cmd = "poetry run python3 telegram_bot.py"
